'use strict';

const md5 = require('md5');
// tests for people
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let getPot = mochaPlugin.getWrapper('people', '/handler.js', 'getPot');
let getAllPots = mochaPlugin.getWrapper('people', '/handler.js', 'getAllPots');
let createPost = mochaPlugin.getWrapper('people', '/handler.js', 'createPost');


describe('people', () => {
  before((done) => {
    done();
  });

  it('implement tests here', async () => {
    let body = {pathParameters: {id: md5(15)}} // 15 is for example md5(15)
    const response = await getPot.run(body);
    expect(response).to.not.be.empty;
  });
});

describe('people', () => {
  before((done) => {
    done();
  });

  it('implement tests here', async () => {
    const response = await getAllPots.run({});
    expect(response).to.not.be.empty;
  });
});


describe('people', () => {
  before((done) => {
    done();
  });

  it('implement tests here', async () => {
    let body = {pathParameters: {number: 15}}
    const response = await createPost.run(body);
    expect(response.body).exist;
  });
});